updates:
  - package-ecosystem: "gradle"
    commit-message:
      prefix: "Update deps"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
      
version: 2
