name: Pull Request CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug
        run: ./gradlew assembleDebug
      - name: Unit-test
        run: ./gradlew test
  check_release_aseemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build internal release
        run: ./gradlew assembleInternal -Dversion_code=${{ github.run_number }} -Dversion_name="0.1.${{ github.run_number }}"
      - name: Prepare key
        run: export DEBUG_KEY=$( openssl base64 < .github/workflows/assets/debug.jks | tr -d '\n' )
      - name: Sign internal release
        id: sign_internal_release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/internal
          signingKeyBase64: ${{ env.DEBUG_KEY }}
          alias: key0
          keyStorePassword: 123456
          keyPassword: 123456