name: Check configuration change
on:
  workflow_call:

jobs:
  check_gradle_files_change:
    name: "Check that gradle files changed"
    runs-on: ubuntu-latest
    outputs:
      GRADLE_FILES_CHANGED: ${{ steps.changed-changelog.outputs.any_changed }}
    steps:
      - name: Check that gradle files changed
        id: changed-changelog
        uses: tj-actions/changed-files@58ae566dc69a926834e4798bcfe0436ff97c0599 # v26.1
        with:
          files: |
            **.gradle.kts
            build-logic/**
            gradle/**
            gradle.properties
  release_build:
    name: "Build release"
    runs-on: [ self-hosted, AndroidShell ]
    needs: check_gradle_files_change
    if: needs.check_gradle_files_change.outputs.GRADLE_FILES_CHANGED == 'true'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build release
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: assembleRelease bundleRelease
  debug_build:
    name: "Build debug"
    runs-on: [ self-hosted, AndroidShell ]
    needs: check_gradle_files_change
    if: needs.check_gradle_files_change.outputs.GRADLE_FILES_CHANGED == 'true'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build debug
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: assembleDebug bundleDebug
  internal_build:
    name: "Build internal"
    runs-on: [ self-hosted, AndroidShell ]
    needs: check_gradle_files_change
    if: needs.check_gradle_files_change.outputs.GRADLE_FILES_CHANGED == 'true'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build internal
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: assembleInternal bundleInternal