name: Check configuration change
on:
  workflow_call:

jobs:
  check_gradle_files_change:
    name: "Check that gradle files changed"
    runs-on: ubuntu-latest
    outputs:
      GRADLE_FILES_CHANGED: ${{ steps.gradle-related-changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: 'recursive'
      - name: Check that gradle files changed
        id: gradle-related-changed
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c # v44.5.7
        with:
          files: |
            **.gradle.kts
            build-logic/**
            gradle/**
            gradle.properties
  matrx_update_gradle:
    name: "Build ${{ matrix.target }}"
    runs-on: ubuntu-latest
    needs: check_gradle_files_change
    if: needs.check_gradle_files_change.outputs.GRADLE_FILES_CHANGED == 'true'
    strategy:
      matrix:
        target: [ "Release", "Debug", "Internal" ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build release
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: assemble${{ matrix.target }} bundle${{ matrix.target }}